### ISSUE TITLE
[Mechanics] - sketches underdefined

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#1]
Sketches for components are underdefined. This creates issues when you need to change model dimensions and the component can react in unexpected ways.
![image](https://user-images.githubusercontent.com/5435954/134519542-e822f2a4-66ca-4910-b40d-b0e97e2f41fd.png)
Can be changed to something like this without issues. It certainly is invalid
![image](https://user-images.githubusercontent.com/5435954/134519626-0b8e87a3-ee74-49f5-b322-186772700d35.png)

Also:
The warnings in components should not be ignored but fixed:
![image](https://user-images.githubusercontent.com/5435954/134519702-6cb5c84c-e5ef-4c54-a9a4-95c942467a47.png)

This feedback goes for all components you created.

**Comment by erkiveevali** [comment]
Resolved the warnings, fixed underdefined sketches where I could find them.

**Comment by Akustav** [comment]
Seems fine now.
