### ISSUE TITLE
[Mechanics] - material thickness is wrong

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#2]
The 5 mm material is in reality 4.8. All components should use this thickness instead of 5.0mm. If you want to use 3 mm PC then the thickness for that is 2.8mm.

**Comment by erkiveevali** [comment]
Thrower components (sidewalls and ramps) are now 4.8mm thick. Motor spacer however needs to be 8mm thick for the motor to be positioned in the center of the thrower, so this needs to be 3D-printed I think.

**Comment by Akustav** [comment]
Okay. Seems fine.
