### ISSUE TITLE
Tweaks to camera parameters

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#27]
I suggest using wider formats like 960x540 or 848X480. Both supports 60 FPS. I would also run the depth camera in 60 FPS.

https://github.com/ut-robotics/picr21-team-kobe/blob/a3beaf545719c4e7e909ae2db7cf378bfad35ff5/CameraConfig.py#L5

**Comment by capnarchie** [comment]
Done
