### ISSUE TITLE
Remote controller code out of date

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#28]
Seems like the remote controller code does not take the updated serial communications system into account.

https://github.com/ut-robotics/picr21-team-kobe/blob/a3beaf545719c4e7e909ae2db7cf378bfad35ff5/RemoteController.py#L27

**Comment by capnarchie** [comment]
Fixed
https://github.com/ut-robotics/picr21-team-kobe/blob/8c389f9f609bdaea94e5cb1c21b49ae8c5c4d79b/RemoteController.py#L13

https://github.com/ut-robotics/picr21-team-kobe/blob/8c389f9f609bdaea94e5cb1c21b49ae8c5c4d79b/RemoteController.py#L34
