### ISSUE TITLE
Weird data returned in image processing

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#30]
https://github.com/ut-robotics/picr21-team-kobe/blob/f1049b4e73890cd247a7a22e3b0cb84c8893d68e/Image_processing.py#L81-L88

Here you return the number of keypoints/balls, and the last keypoints coordinate. This is intended? Why not return a list of ball  x and y coordinates. This list can be checked for length to determine if balls are in the FOV.

I would also rename the return parameter dist. The name is very confusing. What distance is it? Maybe we can even have them as objects, where Ball objects contain the balls x, y location and its size, for example and the Basket object that contains its color, coordinates in the frame, size and its distance

**Comment by capnarchie** [comment]
Yes, I'm intentionally returning the biggest keypoint in the list, which is the first one and its coordinates, this is intended so the robot will go to the nearest (biggest blob size) ball.
