### ISSUE TITLE
Unify code style

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#33]
https://github.com/ut-robotics/picr21-team-kobe/blob/77b2aa011ddafe7fa09fa254b48fecdce3873b44/Image_processing.py#L30

The coding style should be unified. Some methods are capitalized while others, for example in the remote controller code, are lower case.

**Comment by capnarchie** [comment]
Is this a duplicate issue now? In any case coding style should be more unified now.
