### ISSUE TITLE
Don't send debug info to referee's websocket

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-kobe#52]
https://github.com/ut-robotics/picr21-team-kobe/blob/aa76905380af3b117c4471643cc042ce57c5e7a0/Referee_server.py#L31

**Comment by mkroencke** [comment]
Done.

**Comment by ReikoR** [comment]
Debug message is still sent.

https://github.com/ut-robotics/picr21-team-kobe/blob/ba68249b8d43cbb3bcf5c65dd656e7f47c6fae8b/Referee_client.py#L32

**Comment by capnarchie** [comment]
removed debug message sending
