### ISSUE TITLE
[Mechanics] - robot height from the ground

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#6]
How high should the robot be off the ground with its wheels? It is important as it affects how high the motor can be. If it is too high, the ball won't be pulled in and instead bounces off other parts of the chassis. This also allows tuning how low the ramp can be without damaging the carpet or disturbing the robots driving

![image](https://user-images.githubusercontent.com/5435954/134521707-1a4204c1-258e-4ee9-814c-f59d715834f7.png)

**Comment by erkiveevali** [comment]
The bottom plate is around 8mm off the ground right now. The thrower ramp extends 5.5mm from the bottom plate - there should be 2.5mm of clearance between the carpet and the thrower ramps.

**Comment by Akustav** [comment]
Okay, if it is 8mm then everything seems fine.
