### ISSUE TITLE
[Mechanics] - where will the electronics be

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#66]
Currently there is no  electronics installed on the model.

**Comment by erkiveevali** [comment]
Added a quick model of the new PCB to the robot. Other electronics will be mounted to the bottom plate as well, to simplify disassembly.

**Comment by erkiveevali** [comment]
Yes, checked the placement of connectors on the PCB

**Comment by Akustav** [comment]
OK
