### ISSUE TITLE
[Mechanics] - some interferences

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#69]
Some interference in the models. Would be good if they are solved.

![image](https://user-images.githubusercontent.com/5435954/143609811-f116433f-d7a1-414f-9bc1-d4bb6879490b.png)

**Comment by erkiveevali** [comment]
There were some actual interference between the wheels and bottom plate, resolved that. Other interferences between various joints arent supposed to be there because the dimensions of the parts seem correct. And the interferences in the NUC and camera assemblies can be ignored as well.
