### ISSUE TITLE
[Mechanics] - computer impossible to remove unless whole robot is dissasebled

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#71]
Currently the computer is fastened in such a way that the screws are very inaccessible. The whole top needs to be disassembled to remove it. This is intentional?

![image](https://user-images.githubusercontent.com/5435954/143610564-1f444001-717b-4cbb-bfac-6a1aef1c1808.png)

**Comment by erkiveevali** [comment]
The computer can be removed with the plate its mounted to. The screws that hold the plate are accessible from the top and nothing else is holding that plate to the robot. There arent a lot of good ways to make the screws for the NUC itselt accessible unless I mount it upright or upside-down.
