### ISSUE TITLE
[Mechanics] - check internal corners of assemblies

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#72]
Some corners are missing cutouts and need to be manually touched up if not fixed.

![image](https://user-images.githubusercontent.com/5435954/143610987-05100e6a-e72f-4bca-980e-1191a929f5d9.png)

**Comment by erkiveevali** [comment]
Fixed the corners on the picture, didnt find any similar issues elsewhere

**Comment by Akustav** [comment]
New issue appeared with the latch: 
![image](https://user-images.githubusercontent.com/5435954/144111019-adf4a126-3e33-442d-9fee-d05d2e3ede8d.png)

**Comment by erkiveevali** [comment]
Fixed the issue with the latch hole as well.
