### ISSUE TITLE
[Mechanics] - what force holds batteries in the box

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#74]
Question in the title.

**Comment by erkiveevali** [comment]
Friction, mainly. Added a fancy latch? to keep the batteries in there as well. A simple stopper made from a screw and a spacer can be added (as a hack) to the front of the battery compartment if the batteries are really that loose in there. But based to my measurements they should fit snugly in there without any fasteners.

**Comment by Akustav** [comment]
Would like to see the batteries in the box as well, then it is better to see how they are fastened and that they can not move

**Comment by erkiveevali** [comment]
Batteries are now in the box

**Comment by Akustav** [comment]
Can't batteries slip out like this? Maybe you can add a bolt head to the top or bottom to act as a stopper
![image](https://user-images.githubusercontent.com/5435954/144707902-a63557f6-fcd0-4c83-8794-4ccd2114b7d3.png)

**Comment by erkiveevali** [comment]
Added stoppers to the front as well
