### ISSUE TITLE
Use colors to identify side?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#77]
https://github.com/ut-robotics/picr21-team-kobe/blob/86b1d56523d720cfc33aebd9783ef87131fed20b/Robot_runner.py#L46

Color.BLUE and Color.MAGENTA are clearer than a boolean flag.

**Comment by capnarchie** [comment]
done

**Comment by Akustav** [comment]
I currently do not see it as being done. What did you change?

**Comment by capnarchie** [comment]
Reverted the implementation before the competition due to it not working, but now it works.
