### ISSUE TITLE
Is not instead of comparing to None

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#78]
https://github.com/ut-robotics/picr21-team-kobe/blob/86b1d56523d720cfc33aebd9783ef87131fed20b/Robot_runner.py#L71

Can be written as:

`if not state_data.floor_area or state_data.floor_area < 20000:`

**Comment by capnarchie** [comment]
done

**Comment by Akustav** [comment]
In Robot_runner.py I find at least 3 instances of this style of comparison.

**Comment by capnarchie** [comment]
So turns out that `not var` is not the same as `var is  None` and it doesn't pass the if statements then, so `is none` usage is justified.
