### ISSUE TITLE
Serial communications port hardcoded.

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#8]
https://github.com/ut-robotics/picr21-team-kobe/blob/46eb101d32f8b6000470f36c38c8d0c5126a2891/serialcomms.py#L5

Here you have a hardcoded port for serial communications. It is not guaranteed to be on this port. It can be on ttyACM1, for example. IT would be better to create a connection using the target port as an argument.

**Comment by Akustav** [comment]
Yes, since ports are not necessarily deterministic it might be ACM0 but could also be ACM1 if the device, for example is quickly reconnected to the computer.

**Comment by capnarchie** [comment]
https://github.com/ut-robotics/picr21-team-kobe/blob/a54010ddde112ef851a786bccf1b2a4614937434/Movement.py#L5
https://github.com/ut-robotics/picr21-team-kobe/blob/a54010ddde112ef851a786bccf1b2a4614937434/serialcomms.py#L16
Does this still count as hardcoded?

Or do I have to use this and then loop through it to find what serial port is available and then create a connection on that?
https://github.com/ut-robotics/picr21-team-kobe/blob/a54010ddde112ef851a786bccf1b2a4614937434/serialcomms.py#L8
https://github.com/ut-robotics/picr21-team-kobe/blob/a54010ddde112ef851a786bccf1b2a4614937434/serialcomms.py#L10
