### ISSUE TITLE
Use relative numbers based on frame size instead of constants

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#80]
https://github.com/ut-robotics/picr21-team-kobe/blob/86b1d56523d720cfc33aebd9783ef87131fed20b/Robot_runner.py#L88

This is suggested to avoid issues with different resolutions.

**Comment by capnarchie** [comment]
done

**Comment by Akustav** [comment]
You used:

https://github.com/ut-robotics/picr21-team-kobe/blob/34579003f884aa876f4a892da02aef7702d666d4/Robot_runner.py#L128

This is basically the same thing. I suggest using percentages, like:

`state_data.ball_y > Camera.camera_y * 0,88 (=422)`

You can exclude` Camera.camera_y + 20` since it is impossible for the ball to be outside the frame.

**Comment by capnarchie** [comment]
Changed hardcoded resolution dependencies to depend on percentages of resolution instead.
