### ISSUE TITLE
Check area instead of 1 pixel

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#83]
https://github.com/ut-robotics/picr21-team-kobe/blob/86b1d56523d720cfc33aebd9783ef87131fed20b/image_processor.py#L136

Instead of sampling one point, sample a area to get a less noisy result and increase accuracy.

**Comment by capnarchie** [comment]
Done although accuracy is pretty much same for both except for longer distance.

**Comment by Akustav** [comment]
Accuracy contains of both direction and speed. Is the aim direction good/bad? Overall I would check the stability of the measurement when the robot aims at a static object.

**Comment by capnarchie** [comment]
Well it seems good enough that I can not differentiate between the two, so I guess it's working as intended.

**Comment by Akustav** [comment]
One thing you can change for robustness is in case the range gets an out of bounds exception you can fallback to the one-pixel solution. If you do not want to double-check the ranges:

https://github.com/ut-robotics/picr21-team-kobe/blob/1c09a2ff8e201bfb6875c36d273c914e2959c723/image_processor.py#L146-L148
