### ISSUE TITLE
[Mechanics] - Wheel holder bottom plate tab spacing off

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#88]
The spacing should be 60 but for you it is 58,966. This creates some interference issues:
![image](https://user-images.githubusercontent.com/5435954/144111497-5fbbf924-711d-4812-b8dc-fd5d3b811a2b.png)

**Comment by erkiveevali** [comment]
![image](https://user-images.githubusercontent.com/79630265/144657373-20b040bd-5395-4088-a5af-4de6e82bffe1.png)
The dimensions on the sketch are correct, and I am using circular pattern to create 3 identical mounts. Im not sure where this weird number 59.966 comes from

**Comment by Akustav** [comment]
The issue comes from the fact that  this line is not horisontally/vertically aligned. So it is at an angle and that creates a shift
![image](https://user-images.githubusercontent.com/5435954/144707842-e878d17e-48f4-4b95-88fc-5893e9cbfa82.png)

**Comment by erkiveevali** [comment]
All the design issues should be resolved now.
