### ISSUE TITLE
[Mechanics] - add spacer for thrower rigidity

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#89]
Since the thrower motor is fastened on one side I would add a spacer there to add rigidity to the thrower:

![image](https://user-images.githubusercontent.com/5435954/144112066-03cd32a5-ffe9-4953-8d2c-b8dc3dd684df.png)

**Comment by erkiveevali** [comment]
Added the spacer. Since its 44mm in length I will probably have to combine the length from multiple spacers. But should be possible.
