### ISSUE TITLE
[Mechanics] - small circles in CAM only connected with one tab

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#91]
As can be seen small holes are held in with only 1 tab:

![image](https://user-images.githubusercontent.com/5435954/145105735-7a3feb32-628e-4286-8956-e000e067ca71.png)

**Comment by erkiveevali** [comment]
Decreased the minimal distance between tabs, now the small holes have 2 tabs.

**Comment by Akustav** [comment]
Another potential solution you might want to think about is making a separate procedure for these small components. This way you save time on cutting and finishing of the tab residue on the components.

**Comment by erkiveevali** [comment]
The smaller holes already have a separate 2D contour under the setup. You mean getting rid of the tabs on these small cutouts?

**Comment by Akustav** [comment]
Some unintended tabs have appeared? You can also manually place tabs.
![image](https://user-images.githubusercontent.com/5435954/145266849-d1c6741e-62e4-457d-90a8-265f4002962b.png)

**Comment by erkiveevali** [comment]
Placed the tabs manually now, unintended tabs should be gone
