### ISSUE TITLE
[Mechanics] - add some more spacing between components

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kobe#92]
I would increase the spacing between the components a little, this helps avoid pieces flying out of the plate when milled. Examples of close calls:

![image](https://user-images.githubusercontent.com/5435954/145106037-5c6d6515-a236-4df1-b270-6c63e7c0179f.png)
![image](https://user-images.githubusercontent.com/5435954/145106065-4450b748-c669-4900-8b38-a92ac082cc27.png)

**Comment by erkiveevali** [comment]
Increased spacing between components from 6.35mm to 10mm
